#!/bin/sh /etc/rc.common

USE_PROCD=1
START=95
STOP=10

start_service() {
    local port

    config_load sysmon
    config_get port main port 8999

    procd_open_instance
    procd_set_param command python3 /usr/share/sysmon/sysmon-server.py
    procd_set_param env SYSMON_PORT="$port"
    procd_set_param respawn 3600 5 5
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

service_triggers() {
    procd_add_reload_trigger sysmon
}
